name: Release Pipeline

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        required: false
        description: Trigger with publish

jobs:
  publish-private-create:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust-build.yml@v1.1.0
    with:
      skip-test: ${{ github.event_name == 'push' && 'true' || 'false' }}
      publish: ${{ (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.publish)) && 'true' || 'false' }}
      publish_private_registry: true
    secrets: inherit